services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crudlaravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: admin
    networks:
      - laravel-net
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  apache-laravel:
    build: .
    container_name: laravel-app
    networks:
      - laravel-net
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./laravel-app:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crudlaravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=admin

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
